### ISSUE TITLE
代理服务器的Nginx配置能提供下吗

### ISSUE THREAD

**Issue by xubiaolin** [zhuweiyou/chatgpt-api#14]
我想自建一下代理服务器，感谢

**Comment by zhuweiyou** [comment]
你说的是过CF人机的代理吗? 那个没有开源的, 地址来自这里 <https://github.com/transitive-bullshit/chatgpt-api#reverse-proxy>

他说的是 `Note: info on how the reverse proxies work is not being published at this time in order to prevent OpenAI from disabling access.` 防止 OpenAI 和谐, 不开源.

你可以 github / google 搜下 `爬虫绕过 cloudflare 人机验证` 之类的关键词, 好像有类似的库能解决.
